### ISSUE TITLE
Linux: transient authentication failures

### ISSUE THREAD

**Issue by Fitzsimmons** [samm-git/aws-vpn-client#2] opened 2020-10-09 14:29 UTC
Hi, I got this working on Linux!

However, I'm running into a problem where authentication will fail what seems like somewhere between 30 and 50% of the time, with no changes at all between retries:

```AUTH: Received control message: AUTH_FAILED,Invalid username or password```

I'm not familiar enough with the internals of the authentication scheme to know what would cause this. Given the transient nature though, I wonder if maybe the message is being truncated or improperly formatted at some point in the process.

I realize that this issue description isn't much to go on, so if you have any suggestions of other information I could provide, or techniques I could use to narrow down the source of the problem, let me know.

**Comment by samm-git** [comment] 2020-10-10 07:19
I do have one assumption why this could happens. Please provide as much details as possible of your setup, i will try to reproduce

**Comment by lc6chang** [comment] 2020-11-05 10:18
@samm-git I encountered the same issue. My authentication also failed 50% of the time even with no changes at all. Here's my details:

+ OS: MacOS 10.14.5
+ OpenVPN software:
    ```
    OpenVPN 2.4.9 [git:release/2.4/0a178f77282c9051] x86_64-apple-darwin18.6.0 [SSL (OpenSSL)] [LZO] [LZ4] 
    [MH/RECVDA] [AEAD] built on Oct 26 2020
    library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
    Originally developed by James Yonan
    Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
    ```
    I download OpenVPN 2.4.9 source code from GitHub, add your patch then build it.
+ My config (I download it directly from AWS, then modify it):
    ```diff
    client
    dev tun
    proto udp
    remote ... 443
    remote-random-hostname
    resolv-retry infinite
    + route-nopull
    + route ....
    + route ....
    nobind
    + socks-proxy ...
    remote-cert-tls server
    cipher AES-256-GCM
    verb 3
    <ca>
    ...
    </ca>
    - auth-user-pass
    - auth-federate
    - auth-retry interact
    auth-nocache
    reneg-sec 0
    ```
+ My script (I modify it based on your `aws-connect.sh`:
    ```shell
    #!/bin/bash

    set -e

    # path to the patched openvpn
    OVPN_BIN="..."
    # path to the configuration file
    OVPN_CONF="..."
    
    
    wait_file() {
      local file="$1"; shift
      local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout
      until test $((wait_seconds--)) -eq 0 -o -f "$file" ; do sleep 1; done
      ((++wait_seconds))
    }


    # cleanup
    rm -f saml-response.txt

    OVPN_OUT=$($OVPN_BIN --config "${OVPN_CONF}" \
         --auth-user-pass <( printf "%s\n%s\n" "N/A" "ACS::35001" ) \
         2>&1 | grep AUTH_FAILED,CRV1)

    echo "Opening browser and wait for the response file..."
    echo "$OVPN_OUT"
    URL=$(echo "$OVPN_OUT" | grep -Eo 'https://.+')
    echo "$URL"
    open "$URL"

    wait_file "saml-response.txt" 30 || {
      echo "SAML Authentication time out"
      exit 1
    }

    # get SID from the reply
    VPN_SID=$(echo "$OVPN_OUT" | awk -F : '{print $7}')

    echo "Running OpenVPN with sudo. Enter password if requested"
    echo "${VPN_SID}"
    # Finally OpenVPN with a SAML response we got
    # Delete saml-response.txt after connect
    sudo bash -c "$OVPN_BIN --config ${OVPN_CONF} \
        --auth-user-pass <( printf \"%s\n%s\n\" \"N/A\" \"CRV1::${VPN_SID}::$(cat saml-response.txt)\" )"
    ```

+ After I type in my username and password, it redirect to the `go run server.go` page. (In fact I saved my password in my browser so each time it redirects immediately)

+ Then, sometimes the second `openvpn` connection failed and shows me:
    ```
    ...
    Running OpenVPN with sudo. Enter password if requested
    instance-2/****
    Password:
    Thu Nov  5 17:33:56 2020 NOTICE: dual-stack mode for '--proto udp' does not work correctly with '--socks-proxy' today.  Forcing IPv4.
    Thu Nov  5 17:33:56 2020 WARNING: file '/dev/fd/63' is group or others accessible
    Thu Nov  5 17:33:56 2020 OpenVPN 2.4.9 [git:release/2.4/0a178f77282c9051] x86_64-apple-darwin18.6.0 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Oct 26 2020
    Thu Nov  5 17:33:56 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
    Thu Nov  5 17:33:56 2020 WARNING: ignoring --remote-random-hostname because the hostname is an IP address
    Thu Nov  5 17:33:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]****
    Thu Nov  5 17:33:56 2020 Socket Buffers: R=[786896->786896] S=[9216->9216]
    Thu Nov  5 17:33:56 2020 Attempting to establish TCP connection with [AF_INET]****[nonblock]
    Thu Nov  5 17:33:57 2020 TCP connection established with [AF_INET]****
    Thu Nov  5 17:33:57 2020 SOCKS proxy wants us to send UDP to [AF_INET]****
    Thu Nov  5 17:33:57 2020 UDPv4 link local: (not bound)
    Thu Nov  5 17:33:57 2020 UDPv4 link remote: [AF_INET]****
    Thu Nov  5 17:33:58 2020 TLS: Initial packet from [AF_INET]****
    Thu Nov  5 17:33:58 2020 VERIFY OK: depth=1, CN=****
    Thu Nov  5 17:33:58 2020 VERIFY KU OK
    Thu Nov  5 17:33:58 2020 Validating certificate extended key usage
    Thu Nov  5 17:33:58 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
    Thu Nov  5 17:33:58 2020 VERIFY EKU OK
    Thu Nov  5 17:33:58 2020 VERIFY OK: depth=0, CN=****
    Thu Nov  5 17:34:00 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
    Thu Nov  5 17:34:00 2020 [server] Peer Connection Initiated with [AF_INET]****
    Thu Nov  5 17:34:01 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Thu Nov  5 17:34:02 2020 AUTH: Received control message: AUTH_FAILED,Invalid username or password
    Thu Nov  5 17:34:02 2020 SIGTERM[soft,auth-failure] received, process exiting
    ```

**Comment by javiortizmol** [comment] 2020-11-09 19:50
> @samm-git I encountered the same issue. My authentication also failed 50% of the time even with no changes at all. Here's my details:
> 
> * OS: MacOS 10.14.5
> * OpenVPN software:
>   ```
>   OpenVPN 2.4.9 [git:release/2.4/0a178f77282c9051] x86_64-apple-darwin18.6.0 [SSL (OpenSSL)] [LZO] [LZ4] 
>   [MH/RECVDA] [AEAD] built on Oct 26 2020
>   library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
>   Originally developed by James Yonan
>   Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
>   ```
>   
>   
>   I download OpenVPN 2.4.9 source code from GitHub, add your patch then build it.
> * My config (I download it directly from AWS, then modify it):
>   ```diff
>   client
>   dev tun
>   proto udp
>   remote ... 443
>   remote-random-hostname
>   resolv-retry infinite
>   + route-nopull
>   + route ....
>   + route ....
>   nobind
>   + socks-proxy ...
>   remote-cert-tls server
>   cipher AES-256-GCM
>   verb 3
>   <ca>
>   ...
>   </ca>
>   - auth-user-pass
>   - auth-federate
>   - auth-retry interact
>   auth-nocache
>   reneg-sec 0
>   ```
> * My script (I modify it based on your `aws-connect.sh`:
>   ```shell
>   #!/bin/bash
>   
>   set -e
>   
>   # path to the patched openvpn
>   OVPN_BIN="..."
>   # path to the configuration file
>   OVPN_CONF="..."
>   
>   
>   wait_file() {
>     local file="$1"; shift
>     local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout
>     until test $((wait_seconds--)) -eq 0 -o -f "$file" ; do sleep 1; done
>     ((++wait_seconds))
>   }
>   
>   
>   # cleanup
>   rm -f saml-response.txt
>   
>   OVPN_OUT=$($OVPN_BIN --config "${OVPN_CONF}" \
>        --auth-user-pass <( printf "%s\n%s\n" "N/A" "ACS::35001" ) \
>        2>&1 | grep AUTH_FAILED,CRV1)
>   
>   echo "Opening browser and wait for the response file..."
>   echo "$OVPN_OUT"
>   URL=$(echo "$OVPN_OUT" | grep -Eo 'https://.+')
>   echo "$URL"
>   open "$URL"
>   
>   wait_file "saml-response.txt" 30 || {
>     echo "SAML Authentication time out"
>     exit 1
>   }
>   
>   # get SID from the reply
>   VPN_SID=$(echo "$OVPN_OUT" | awk -F : '{print $7}')
>   
>   echo "Running OpenVPN with sudo. Enter password if requested"
>   echo "${VPN_SID}"
>   # Finally OpenVPN with a SAML response we got
>   # Delete saml-response.txt after connect
>   sudo bash -c "$OVPN_BIN --config ${OVPN_CONF} \
>       --auth-user-pass <( printf \"%s\n%s\n\" \"N/A\" \"CRV1::${VPN_SID}::$(cat saml-response.txt)\" )"
>   ```
> * After I type in my username and password, it redirect to the `go run server.go` page. (In fact I saved my password in my browser so each time it redirects immediately)
> * Then, sometimes the second `openvpn` connection failed and shows me:
>   ```
>   ...
>   Running OpenVPN with sudo. Enter password if requested
>   instance-2/****
>   Password:
>   Thu Nov  5 17:33:56 2020 NOTICE: dual-stack mode for '--proto udp' does not work correctly with '--socks-proxy' today.  Forcing IPv4.
>   Thu Nov  5 17:33:56 2020 WARNING: file '/dev/fd/63' is group or others accessible
>   Thu Nov  5 17:33:56 2020 OpenVPN 2.4.9 [git:release/2.4/0a178f77282c9051] x86_64-apple-darwin18.6.0 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Oct 26 2020
>   Thu Nov  5 17:33:56 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
>   Thu Nov  5 17:33:56 2020 WARNING: ignoring --remote-random-hostname because the hostname is an IP address
>   Thu Nov  5 17:33:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]****
>   Thu Nov  5 17:33:56 2020 Socket Buffers: R=[786896->786896] S=[9216->9216]
>   Thu Nov  5 17:33:56 2020 Attempting to establish TCP connection with [AF_INET]****[nonblock]
>   Thu Nov  5 17:33:57 2020 TCP connection established with [AF_INET]****
>   Thu Nov  5 17:33:57 2020 SOCKS proxy wants us to send UDP to [AF_INET]****
>   Thu Nov  5 17:33:57 2020 UDPv4 link local: (not bound)
>   Thu Nov  5 17:33:57 2020 UDPv4 link remote: [AF_INET]****
>   Thu Nov  5 17:33:58 2020 TLS: Initial packet from [AF_INET]****
>   Thu Nov  5 17:33:58 2020 VERIFY OK: depth=1, CN=****
>   Thu Nov  5 17:33:58 2020 VERIFY KU OK
>   Thu Nov  5 17:33:58 2020 Validating certificate extended key usage
>   Thu Nov  5 17:33:58 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
>   Thu Nov  5 17:33:58 2020 VERIFY EKU OK
>   Thu Nov  5 17:33:58 2020 VERIFY OK: depth=0, CN=****
>   Thu Nov  5 17:34:00 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
>   Thu Nov  5 17:34:00 2020 [server] Peer Connection Initiated with [AF_INET]****
>   Thu Nov  5 17:34:01 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
>   Thu Nov  5 17:34:02 2020 AUTH: Received control message: AUTH_FAILED,Invalid username or password
>   Thu Nov  5 17:34:02 2020 SIGTERM[soft,auth-failure] received, process exiting
>   ```

Hi @lc6chang, How did you solved?

**Comment by lc6chang** [comment] 2020-11-10 01:19
@javiortizmol https://github.com/samm-git/aws-vpn-client/issues/2#issuecomment-724240151 Have not solved yet, still 50% available. But AWS VPN Client software always works well.

**Comment by mj3c** [comment] 2020-11-12 11:41
I tried [URL decoding](https://stackoverflow.com/a/37840948/6247093) the SAML response before passing it to `auth-user-pass` (see below) but the behavior is the same, it authenticates successfully only sometimes.

```bash
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

# Finally OpenVPN with a SAML response we got
# Delete saml-response.txt after connect
bash -c "/openvpn --config /vpn.modified.conf \
         --verb 3 --auth-nocache --inactive 3600 \
         --proto $PROTO --remote $SRV $PORT \
         --script-security 2 \
         --route-up '/bin/rm saml-response.txt' \
         --auth-user-pass <( printf \"%s\n%s\n\" \"N/A\" \"CRV1::${VPN_SID}::$(urldecode $(cat saml-response.txt))\" )"
```

**Edit:** Also, I thought maybe it depends on the exact server/IP that is accepting the connection, but I found that whether it manages to connect or not has no correlation to the server/IP, so that probably is not the issue.

@samm-git Could you share what you believe might be the cause of this?

**Comment by samm-git** [comment] 2020-11-15 10:25
Hi, i am 90% sure that cause is very simple - native client keeps tcp connection open and my implementation not. I will try to fix that but no timelines, very busy atm

**Comment by samm-git** [comment] 2020-11-15 10:25
(plus i want to think how to make it _properly_)

**Comment by othmane399** [comment] 2021-01-28 18:52
Hi @samm-git , Thanks for what you have already do. I'm facing the same issue as well. Which TCP connection you are talking about ? I can help you

**Comment by samm-git** [comment] 2021-02-01 13:50
Hi, i think i will try to find some time today or tomorrow to fix that

**Comment by lost-osiris** [comment] 2021-02-03 08:30
@samm-git I've found that using your patch or the latest `acvc-openvpn` binary produces the same error. I did notice that when you use the AWS VPN Client OS X app that it uses `--management 127.0.0.1 8096 ~/.config/AWSVPNClient/acvc-8096.txt --management-query-passwords` 

The content of `acvc-8096.txt` is some hash, not sure if its conned to the session at all. This file gets cleared out once the connection is successfully made. Had to put a `tail` in a loop just to be able to see what was written to it. The AWS VPN Client app also modifies your config with an `up` and `down` script. Tried to sort through those but its difficult to follow. 

At this point I've does everything I can think of to debug, @samm-git if you or anyone else has anymore insights that would be greatly appreciated!

**Comment by othmane399** [comment] 2021-02-15 09:18
Hello @lost-osiris , I have the latest `acvc-openvpn` and here's my assumptions:
- `~/.config/AWSVPNClient/acvc-8096.txt` is related to the interface password (so that not affect the script that @samm-git provide)
- I've captured the traffic that pass in the interface management console, and I can say that the protocol (logic) still the same as what is implemented by @samm-git 
So I'm pretty confident that is only the tcp lost connection is the main issue of this thread.

**Comment by ghost** [comment] 2021-02-25 23:24
I'm getting this 100% of the time. It's possible I just haven't set this up correctly (i.e. it's PEBKAC) but I'm not sure what I'd be doing wrong.

I'm on Arch and basically just got the 2.4.9 version of the PKGBUILD [here](https://github.com/archlinux/svntogit-packages/blob/231f2e08f8995599ccd506f34d441e88192e803c/trunk/PKGBUILD) and added the aws patch. I then took the same profile that works on the macOS AWS client, removed the `auth-user-pass`, `auth-federate`, and `auth-retry-interact` lines, updated aws-connect.sh to point to the vpn config host/port/protocol, and altered `open` to `xdg-open` since `open` is not a valid command in Linux.

Example output of what I see:

```
OpenVPN 2.4.9 [git:makepkg/9b0dafca6c50b8bb+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 24 2021
library versions: OpenSSL 1.1.1j  16 Feb 2021, LZO 2.10
NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
TCP/UDP: Preserving recently used remote address: [AF_INET]54.XXX.XXX.XXX:1194
Socket Buffers: R=[212992->212992] S=[212992->212992]
UDP link local: (not bound)
UDP link remote: [AF_INET]54.XXX.XXX.XXX:1194
TLS: Initial packet from [AF_INET]54.XXX.XXX.XXX:1194, sid=35XXXXXX 5111XXXX
VERIFY OK: depth=1, CN=[snip]
VERIFY KU OK
Validating certificate extended key usage
++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
VERIFY EKU OK
VERIFY OK: depth=0, CN=server
Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
[server] Peer Connection Initiated with [AF_INET]54.XXX.XXX.XXX:1194
SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
AUTH: Received control message: AUTH_FAILED,Invalid username or password
SIGTERM[soft,auth-failure] received, process exiting
```

While debugging it does seem like all of the values are properly populated but perhaps I'm missing something?

Here's example output of what I see when setting -x:

```
+ sudo bash -c './openvpn --config prod.ovpn     --verb 3 --auth-nocache --inactive 3600     --proto udp --remote 54.XXX.XXX.XXX 1194     --script-security 2     --route-up '\''/bin/rm saml-response.txt'\''     --auth-user-pass <( printf "%s\n%s\n" "N/A" "CRV1::instance-1/693XXXXXXXXX/c9XXXXXX-c7XX-XXXX-XXXX-XXXXXXXXXX::PD94bWwgdmVyc2lvbj0[.................SNIP.............]vc2FtbDJwOlJlc3BvbnNlPg%3D%3D" )'
```

Is this related or am I just simply doing it wrong?

[Edit] To clarify, I am using the Go proxy and it successfully authenticates via Okta each time. I also tried compiling with simpler steps than the Arch PKGBUILD and also with AWS' published source code. Nada.

**Comment by adamantike** [comment] 2021-03-01 03:47
I am also experiencing the same issue. I have run each command from the `aws-connect.sh` script manually, until the `saml-response.txt` file is generated and the `VPN_SID` variable is populated. After that, running the last command to initiate the OpenVPN client fails sometimes, but is even transient when retrying with the same `saml-response.txt` content, which should indicate that this is not an encoding or server authentication issue.

I am also willing to help with triaging/debugging.

**Comment by VincentDugard** [comment] 2021-03-17 14:16
@samm-git Any new on this ? I have the same problem

**Comment by raids** [comment] 2021-03-18 16:36
Thanks for the work you've put into creating this so far. I'm also willing to help debug/test the transient failures if needed.

**Comment by samm-git** [comment] 2021-03-18 21:07
Hopefully will find some time next week. Should be easy to fix but will need some rework

**Comment by adamantike** [comment] 2021-03-19 15:51
@samm-git, do you have any context from the top of your head that you can share, in case someone else wants to give it a try in the meantime? :)

**Comment by rdvencioneck** [comment] 2021-03-29 02:30
Hi, I was also experiencing this, but after some tests I came to the conclusion that it seemed like the `--remote` option was not overriding the `remote` defined inside the conf file.

So I just included a sed command in the script to remove the `remote` line before running `$OVPN_BIN` and it worked 100% of the time for me.

**Comment by mj3c** [comment] 2021-03-29 07:23
I just tried that @rdvencioneck, actually I removed the `remote` from the conf file entirely, as it is defined in `./aws-connect.sh`... but I still get the same error :confused: 

```
AUTH: Received control message: AUTH_FAILED,Invalid username or password
```

**Comment by samm-git** [comment] 2021-03-29 10:22
finally got some time working on that. will try to do some updates this week

**Comment by indrekj** [comment] 2021-04-16 11:42
I had exactly the same problem. I often got "AUTH_FAILED" and it took many tries to establish a connection. But I think I solved at least my case.

The problem seemed to be that the first and second openvpn commands use different remote IP addresses. It seems that `--remote` flag doesn't work when the `vpn.conf` includes `remote` line. So basically what I did:
1. Removed `remote` and `remote-random-hostname` from `vpn.conf`.
2. In `aws-connect.sh` changed port from 1194 to 443. Also make sure VPN_HOST is correct.

So far I have not seen any AUTH_FAILED messages, but I've only used it for a day.

**Comment by samm-git** [comment] 2021-04-16 14:30
@indrekj oh thank you for that. I had no remote line in my config and this is why i was not able to reproduce. Indeed this is likely a case!

**Comment by ghost** [comment] 2021-04-16 16:25
Yes, this seems to have fixed it for me as well.

**Comment by samm-git** [comment] 2021-04-16 16:49
Thank you, i just added information about it in readme. Closing this, feel free to reopen if needed.

**Closed as completed by samm-git** 2021-04-16 16:49 UTC
