### ISSUE TITLE
AUTH: Received control message: AUTH_FAILED,Invalid username or password

### ISSUE THREAD

**Issue by moserke** [samm-git/aws-vpn-client#5] opened 2021-03-29 23:09 UTC
Thanks so much for this amazing deep dive.  I've learned a lot about what the AWS VPN is doing under the covers.  I've tried getting this to work on OSX (as a test to then work on linux) and I can get openvpn compiled and can get all the way through the saml handshake but no matter what I try I simply can not get it to fully auth.

I have tried both a udp and tcp VPC endpoint and various other things I can think of.  As well as modifying the server.go to not url.QueryEscape() wondering if this is something that would change things.  No matter what I try I can't seem to get past the auth failed.

Below is my config.

```
client
dev tun
proto tcp
resolv-retry infinite
nobind
remote-cert-tls server
cipher AES-256-GCM
verb 3
<ca>
--TRIMMED--
</ca>

auth-nocache
reneg-sec 0
```

I recognize this is a bit of a "see anything wrong" with not a lot of details request, so can understand if there is not you can do from this.  I feel like I am "so close" on getting this working and it must just be something simple I'm missing.  Below is the output of my connection attempts

```
Mon Mar 29 16:06:53 2021 WARNING: file '/dev/fd/63' is group or others accessible
Mon Mar 29 16:06:53 2021 OpenVPN 2.4.9 x86_64-apple-darwin19.6.0 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] built on Mar 26 2021
Mon Mar 29 16:06:53 2021 library versions: OpenSSL 1.1.1j  16 Feb 2021, LZO 2.10
Mon Mar 29 16:06:53 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Mar 29 16:06:53 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]<redacted>:443
Mon Mar 29 16:06:53 2021 Socket Buffers: R=[131072->131072] S=[131072->131072]
Mon Mar 29 16:06:53 2021 Attempting to establish TCP connection with [AF_INET]<redacted>:443 [nonblock]
Mon Mar 29 16:06:54 2021 TCP connection established with [AF_INET]<redacted>:443
Mon Mar 29 16:06:54 2021 TCP_CLIENT link local: (not bound)
Mon Mar 29 16:06:54 2021 TCP_CLIENT link remote: [AF_INET]<redacted>:443
Mon Mar 29 16:06:54 2021 TLS: Initial packet from [AF_INET]<redacted>:443, sid=8cb8040f 77016deb
Mon Mar 29 16:06:54 2021 VERIFY OK: depth=3, C=US, ST=Arizona, L=Scottsdale, O=Starfield Technologies, Inc., CN=Starfield Services Root Certificate Authority - G2
Mon Mar 29 16:06:54 2021 VERIFY OK: depth=2, C=US, O=Amazon, CN=Amazon Root CA 1
Mon Mar 29 16:06:54 2021 VERIFY OK: depth=1, C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
Mon Mar 29 16:06:54 2021 VERIFY KU OK
Mon Mar 29 16:06:54 2021 Validating certificate extended key usage
Mon Mar 29 16:06:54 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Mon Mar 29 16:06:54 2021 VERIFY EKU OK
Mon Mar 29 16:06:54 2021 VERIFY OK: depth=0, CN=*.scpsbx.net
Mon Mar 29 16:06:54 2021 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Mon Mar 29 16:06:54 2021 [*.scpsbx.net] Peer Connection Initiated with [AF_INET]<redacted>:443
Mon Mar 29 16:06:56 2021 SENT CONTROL [*.scpsbx.net]: 'PUSH_REQUEST' (status=1)
Mon Mar 29 16:06:56 2021 AUTH: Received control message: AUTH_FAILED,Invalid username or password
Mon Mar 29 16:06:56 2021 SIGTERM[soft,auth-failure] received, process exiting
```

The only difference I see here versus in the native AWS client logs is that there are two `PUSH_REQUEST` messages in the native log.

If there is anything that jumps out at you I'd be grateful for the assist.  But I also realize this is not a lot to go on and so if nothing jumps out that's ok and appreciate at least taking the time to scan the details.

Thanks!

**Comment by lumi-pwhitney** [comment] 2021-04-05 18:44
We've been testing this out for a small number (under 5) of linux clients we would need to connect to the vpn.  We're experiencing the same issue.  Here is a snip of the logs from where it fails (note: the peer connection was to the exact same IP both times): 

**Unsuccessful:**
`
Mon Apr  5 14:27:31 2021 VERIFY EKU OK
Mon Apr  5 14:27:31 2021 VERIFY OK: depth=0, CN=<redacted>.com
Mon Apr  5 14:27:31 2021 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Mon Apr  5 14:27:31 2021 [<redacted>.com] Peer Connection Initiated with [AF_INET]52.54.xxx.yyy:1194
Mon Apr  5 14:27:32 2021 SENT CONTROL [<redacted>.com]: 'PUSH_REQUEST' (status=1)
Mon Apr  5 14:27:32 2021 AUTH: Received control message: AUTH_FAILED,Invalid username or password
Mon Apr  5 14:27:32 2021 SIGTERM[soft,auth-failure] received, process exiting
`

**Successful:**
`
Mon Apr  5 14:28:17 2021 VERIFY EKU OK
Mon Apr  5 14:28:17 2021 VERIFY OK: depth=0, CN=<redacted>.com
Mon Apr  5 14:28:17 2021 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Mon Apr  5 14:28:17 2021 [<redacted>.com] Peer Connection Initiated with [AF_INET]52.54.xxx.yyy:1194
Mon Apr  5 14:28:18 2021 SENT CONTROL [<redacted>.com]: 'PUSH_REQUEST' (status=1)
Mon Apr  5 14:28:18 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,route-gateway 10.17.0.33,topology subnet,ping 1,ping-restart 20,ifconfig 10.17.0.34 255.255.255.224,peer-id 0,cipher AES-256-GCM'
`

**Comment by samm-git** [comment] 2021-04-16 17:06
I recently updated patch and documentation. Please let me know if changes fixing your issue.

**Comment by andrei-ivanov-pie** [comment] 2021-04-19 19:42
Using the 2.5.1 patch, I'm getting the same error as above.
I see the browser open, get the "Got SAMLResponse field, it's safe to close this window" page.
The aws_connect.sh exits with this:
`2021-04-19 13:36:20 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2021-04-19 13:36:20 VERIFY EKU OK
2021-04-19 13:36:20 VERIFY OK: depth=0, CN=*.com
2021-04-19 13:36:20 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
2021-04-19 13:36:20 [*.com] Peer Connection Initiated with [AF_INET]35.81.112.236:443
2021-04-19 13:36:21 SENT CONTROL [*.com]: 'PUSH_REQUEST' (status=1)
2021-04-19 13:36:21 AUTH: Received control message: AUTH_FAILED,Invalid username or password
2021-04-19 13:36:21 SIGTERM[soft,auth-failure] received, process exiting
`

To avoid any problems I've used our vpn.conf and followed your instructions to remove unsupported fields.
`client
dev tun
proto tcp
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
verb 3
<ca>
-----BEGIN CERTIFICATE-----
<snipped>
-----END CERTIFICATE-----

</ca>

auth-nocache
reneg-sec 0
`

I had to change the port in aws_connect from 1194 to 443 to get it to work at all.
When I connect using the AWS VPN Client on Windows, the message I get in browser is "Authentication details received, processing details. You may close this window at any time.". When connecting through your solution, the message I get in browser is "Got SAMLResponse field". Not sure if that makes a difference.

**Comment by samm-git** [comment] 2021-04-22 18:17
@andrei-ivanov-pie different text does not matter, its expected. Which IDP do you use? Does it work fine on native client?

**Comment by andrei-ivanov-pie** [comment] 2021-04-22 19:29
We use Okta. The AWS VPN client works fine on Windows with the vpn config file above (minus the fields that were removed per your instructions)

**Comment by samm-git** [comment] 2021-04-23 08:10
@andrei-ivanov-pie this is very strange, i use okta as well. If you can make me some "guest" testing account i can test. As i cant reproduce it on my side otherwise.

**Comment by andrei-ivanov-pie** [comment] 2021-04-23 20:07
@samm-git Actually, after a reboot it now works! I'm successfully able to connect. Thank you for this awesome patch.

**Closed as completed** 2021-04-23 22:16 UTC

**Comment by furai** [comment] 2021-06-01 08:06
I'm experiencing very random results with connecting. We're authenticating using okta. Sometimes it connects after 2-3 tries, sometimes it takes 10 or more. It just says that auth failed. Any pointers on how i could debug what's going on?

**Comment by adamantike** [comment] 2021-06-01 13:28
@furai, we were also experiencing authentication issues while using Okta. However, after the discussions in #2, we stabilized our auth attemps, by removing the following fields from the VPN configuration file: https://github.com/samm-git/aws-vpn-client/blob/0f206a7985c7feb24a27b97ea6920796f2007322/README.md#additional-steps
